apiVersion: v1
kind: Endpoints
metadata:
  name: redis-cluster
  namespace: default
subsets:
  - addresses:
    - ip: 10.1.0.32
    ports:
      - port: 6379
      
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
spec:
  ports:
  - port: 6379